ARG BASE_IMAGE=cobalt-build-evergreen:latest
FROM ${BASE_IMAGE}

USER root
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake \
    && rm -rf /var/lib/apt/lists/*
